### ISSUE TITLE
URI has an authority component

### ISSUE THREAD

**Issue by habibutsu** [spidasoftware/mongodb-geoserver#20]
If try to add datastore with URI `mongodb://192.168.100.3/test`, the following error occurs:

`Error creating data store, check the parameters. Error message: URI has an authority component`

GeoServer Version: 2.20.1

**Comment by spidaMikeFord** [comment]
Is that in the "host" field? The host value is passed to a Mongo ServerAddress.

https://github.com/spidasoftware/mongodb-geoserver/blob/master/src/main/groovy/com/spidasoftware/mongodb/data/MongoDBDataAccess.groovy#L143

https://mongodb.github.io/mongo-java-driver/3.6/javadoc/?com/mongodb/ServerAddress.html

It is expecting just the hostname, I believe, not a full URI.

**Comment by habibutsu** [comment]
@spidaMikeFord field has name `data_store` and in according with example (default value ` mongodb://localhost/<database name>`) should have full uri. There is no way to specify host separately

![Screenshot from 2022-01-08 00-13-02](https://user-images.githubusercontent.com/1193481/148608219-7a4dda6f-d9a4-4d66-beba-3f782cce9da0.png)
.
